# Generated by Django 5.2.5 on 2025-08-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/avatars/'),
        ),
        migrations.AddField(
            model_name='master',
            name='nickname',
            field=models.CharField(default='Крутой лысый гоблин', max_length=30, verbose_name='Псевдоним мастера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/avatars/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=30, verbose_name='Псевдоним игрока'),
        ),
    ]
