# Generated by Django 5.2.5 on 2025-08-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='base_slug', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
