# Generated by Django 5.2.5 on 2025-08-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_post_options_alter_post_rating_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='armor_class',
            field=models.PositiveIntegerField(default=0, verbose_name='КД'),
        ),
        migrations.AddField(
            model_name='creature',
            name='body_condition',
            field=models.PositiveIntegerField(choices=[(20, 20), (19, 19), (18, 18), (17, 17), (16, 16), (15, 15), (14, 14), (13, 13), (12, 12), (11, 11), (10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=10, verbose_name='Телосложение'),
        ),
        migrations.AddField(
            model_name='creature',
            name='charisma',
            field=models.PositiveIntegerField(choices=[(20, 20), (19, 19), (18, 18), (17, 17), (16, 16), (15, 15), (14, 14), (13, 13), (12, 12), (11, 11), (10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=10, verbose_name='Харизма'),
        ),
        migrations.AddField(
            model_name='creature',
            name='dangerous_level',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, verbose_name='Опасность'),
        ),
        migrations.AddField(
            model_name='creature',
            name='dexterity',
            field=models.PositiveIntegerField(choices=[(20, 20), (19, 19), (18, 18), (17, 17), (16, 16), (15, 15), (14, 14), (13, 13), (12, 12), (11, 11), (10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=0, verbose_name='Ловкость'),
        ),
        migrations.AddField(
            model_name='creature',
            name='health',
            field=models.PositiveIntegerField(default=0, verbose_name='Хиты'),
        ),
        migrations.AddField(
            model_name='creature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wiki/creature_images/'),
        ),
        migrations.AddField(
            model_name='creature',
            name='intelligence',
            field=models.PositiveIntegerField(choices=[(20, 20), (19, 19), (18, 18), (17, 17), (16, 16), (15, 15), (14, 14), (13, 13), (12, 12), (11, 11), (10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=10, verbose_name='Интеллект'),
        ),
        migrations.AddField(
            model_name='creature',
            name='mastery',
            field=models.PositiveIntegerField(choices=[(1, '+1'), (2, '+2'), (3, '+3'), (4, '+4'), (5, '+5'), (6, '+6'), (7, '+7'), (8, '+8'), (9, '+9'), (10, '+10')], default=10, verbose_name='Бонус мастерства'),
        ),
        migrations.AddField(
            model_name='creature',
            name='saving_throws',
            field=models.CharField(default='', max_length=500, verbose_name='Спасброски'),
        ),
        migrations.AddField(
            model_name='creature',
            name='size',
            field=models.CharField(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('giant', 'Giant')], default=''),
        ),
        migrations.AddField(
            model_name='creature',
            name='skills',
            field=models.CharField(default='', max_length=500, verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='creature',
            name='speed',
            field=models.PositiveIntegerField(default=0, verbose_name='Скорость'),
        ),
        migrations.AddField(
            model_name='creature',
            name='strength',
            field=models.PositiveIntegerField(choices=[(20, 20), (19, 19), (18, 18), (17, 17), (16, 16), (15, 15), (14, 14), (13, 13), (12, 12), (11, 11), (10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=10, verbose_name='Сила'),
        ),
        migrations.AddField(
            model_name='creature',
            name='wisdom',
            field=models.PositiveIntegerField(choices=[(20, 20), (19, 19), (18, 18), (17, 17), (16, 16), (15, 15), (14, 14), (13, 13), (12, 12), (11, 11), (10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=10, verbose_name='Мудрость'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание существа'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название существа'),
        ),
    ]
