# Generated by Django 5.2.5 on 2025-08-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_creature_armor_class_creature_body_condition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория существ', 'verbose_name_plural': 'Категории существ'},
        ),
    ]
