# Generated by Django 5.2.5 on 2025-08-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_postcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
