# Generated by Django 5.2.5 on 2025-08-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_creature_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creaturecategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория существ', 'verbose_name_plural': 'Категории существ'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={},
        ),
        migrations.AlterField(
            model_name='creature',
            name='dexterity',
            field=models.PositiveIntegerField(choices=[(20, 20), (19, 19), (18, 18), (17, 17), (16, 16), (15, 15), (14, 14), (13, 13), (12, 12), (11, 11), (10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=10, verbose_name='Ловкость'),
        ),
    ]
