# Generated by Django 5.2.5 on 2025-08-12 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_creaturecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wiki/spell_category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SpellEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True)),
                ('text', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Эффект заклинания',
                'verbose_name_plural': 'Эффекты заклинания',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='creature',
            options={'ordering': ('name',), 'verbose_name': 'Существо', 'verbose_name_plural': 'Существа'},
        ),
        migrations.AlterModelOptions(
            name='creatureattack',
            options={'ordering': ('name',), 'verbose_name': 'Атака существа', 'verbose_name_plural': 'Атаки существ'},
        ),
        migrations.AlterModelOptions(
            name='creaturepassive',
            options={'ordering': ('name',), 'verbose_name': 'Особенность существа', 'verbose_name_plural': 'Особенности существ'},
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wiki/spell_images/')),
                ('spell_level', models.CharField(choices=[('заговор', 'Заговор'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100, verbose_name='Уровень заклинания')),
                ('requreiments', models.CharField(default='отсутствуют', max_length=300, verbose_name='Требования')),
                ('special_components', models.CharField(default='отсутствуют', max_length=300, verbose_name='Особые компоненты')),
                ('effects', models.ManyToManyField(related_name='spells', to='wiki.spelleffect')),
            ],
            options={
                'verbose_name': 'Заклинание',
                'verbose_name_plural': 'Заклинания',
                'ordering': ('title',),
            },
        ),
    ]
