# Generated by Django 5.2.5 on 2025-08-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_spellcategory_spelleffect_alter_creature_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spell',
            options={'ordering': ('name',), 'verbose_name': 'Заклинание', 'verbose_name_plural': 'Заклинания'},
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='spell',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='wiki.spellcategory'),
        ),
    ]
