# Generated by Django 5.2.5 on 2025-08-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_alter_spell_options_rename_title_spell_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='effects',
        ),
        migrations.AlterField(
            model_name='spell',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='wiki.spellcategory'),
        ),
        migrations.CreateModel(
            name='SpellEffectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.spelleffect')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.spell')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('spell', 'effect')},
            },
        ),
    ]
