# Generated by Django 5.2.5 on 2025-08-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_remove_spell_effects_alter_spell_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='effects',
            field=models.ManyToManyField(blank=True, related_name='spells', through='wiki.SpellEffectLink', to='wiki.spelleffect'),
        ),
    ]
