# Generated by Django 5.2.5 on 2025-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_spell_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='spelleffectlink',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
