# Generated by Django 5.2.5 on 2025-08-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_spelleffectlink_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spelleffectlink',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='spelleffectlink',
            name='order',
        ),
    ]
