# Generated by Django 5.2.5 on 2025-08-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_alter_spelleffectlink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время накладывания'),
        ),
        migrations.AddField(
            model_name='spell',
            name='distance',
            field=models.CharField(blank=True, help_text='На себя/10 футов/30 футов', max_length=100, null=True, verbose_name='Дистанция'),
        ),
        migrations.AddField(
            model_name='spell',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Длительность'),
        ),
    ]
