# Generated by Django 5.2.5 on 2025-08-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_spell_casting_time_spell_distance_spell_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='requirements',
            field=models.CharField(default='отсутствуют', max_length=300, verbose_name='Требования'),
        ),
    ]
