# Generated by Django 5.2.5 on 2025-08-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_spell_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='requreiments',
        ),
    ]
