# Generated by Django 5.2.5 on 2025-08-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0019_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('title',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('title',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
