# Generated by Django 5.2.5 on 2025-08-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0020_alter_news_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spellcategory',
            options={'ordering': ('name',), 'verbose_name': 'Категория заклинаний', 'verbose_name_plural': 'Категории заклинаний'},
        ),
    ]
