# Generated by Django 5.2.5 on 2025-08-21 16:34

import apps.shop.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL категории')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тег')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL тега')),
            ],
            options={
                'verbose_name': 'Тег товаров',
                'verbose_name_plural': 'Теги товаров',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL товара')),
                ('description', models.TextField(max_length=600, verbose_name='Описание')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество в наличии')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('prom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Акционная цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productcategory', verbose_name='Категория товара')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.shop.models.product_image_upload_to)),
                ('is_main', models.BooleanField(default=False, verbose_name='Обложка')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product',), name='unique_main_image_per_product'), models.UniqueConstraint(fields=('product', 'position'), name='unique_image_position_per_product')],
            },
        ),
    ]
