# Generated by Django 5.2.5 on 2025-08-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_options_product_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTags',
            new_name='ProductTag',
        ),
    ]
