# Generated by Django 5.2.5 on 2025-08-26 14:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_tags_product_product_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_count', models.PositiveIntegerField(verbose_name='Позитивные голоса')),
                ('down_count', models.PositiveIntegerField(verbose_name='Негативные голоса')),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=2, verbose_name='Рейтинг (1.0-5.0)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='shop.product')),
            ],
            options={
                'verbose_name': 'Рейтинг товаров',
                'verbose_name_plural': 'Рейтинги товаров',
                'ordering': ('rating',),
            },
        ),
        migrations.CreateModel(
            name='ProductVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'up'), (-1, 'down')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='shop.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценки товаров',
                'verbose_name_plural': 'Оценки товаров',
                'ordering': ('pk',),
                'constraints': [models.UniqueConstraint(fields=('product', 'user'), name='unique_user_vote_for_product')],
            },
        ),
    ]
