# Generated by Django 5.2.5 on 2025-08-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productrating_productvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='down_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Негативные голоса'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='up_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Позитивные голоса'),
        ),
    ]
