# Generated by Django 5.2.5 on 2025-08-29 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productreview',
            name='unique_user_review_per_product',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='shop_produc_product_705e6f_idx',
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'is_deleted', '-created_at'], name='shop_produc_product_5d853f_idx'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('product', 'user'), name='unique_user_review_per_product'),
        ),
    ]
